baseURL = "https://opencensus.io/api/php/"
languageCode = "en-us"
title = "OpenCensus for PHP"
theme = "hyde"

pygmentsCodeFences = true
pygmentsOptions = "startinline=false"

[params]
  description = "A stats collection and distributed tracing framework"

[[menu.main]]
  name = "API Documentation"
  url = "/api"
  weight = -10
